# Generated by Django 4.0.5 on 2022-06-13 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150, verbose_name='Имя, Фамилия, Отчество')),
                ('prof_skills', models.TextField(verbose_name='Профессиональные навыки')),
                ('social_skills', models.TextField(verbose_name='Социальные навыки')),
                ('start_work', models.DateField(verbose_name='Принят на работу')),
                ('end_work', models.DateField(verbose_name='Окончание работы')),
                ('photo', models.ImageField(blank=True, upload_to='images/%y/%m/%d/', verbose_name='Фото')),
                ('job_title', models.CharField(max_length=150, verbose_name='Должность')),
                ('duty', models.TextField(verbose_name='Обязанности')),
                ('Now_job', models.CharField(max_length=150, verbose_name='Желаемая должность')),
                ('money', models.IntegerField(verbose_name='Уровень ЗП')),
                ('contacts', models.TextField(verbose_name='Мои контакты')),
            ],
        ),
    ]
